PWD :=$(shell pwd)/usb/

all:
	make -C $(PWD)

clean:
	make clean -C $(PWD)
##############################################################################

install:
	make install -C $(PWD)

uninstall:
	make uninstall -C $(PWD)
